import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Nav from '@components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fullstory',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
            <div className="gradient" />
        </div>
        <div className="app">
          <Nav />
          {children}
        </div>
        </body>
    </html>
  )
}
